name: Code Check,Tests

on:
  push:
    branches-ignore:
      - main
  workflow_dispatch:

jobs:
  lint-check:
    name: Lint Code Check
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write
    
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Send Telegram notification - Lint started
        uses: appleboy/telegram-action@v0.1.1
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            🔍 Началась проверка кода линтером!
            Репозиторий: ${{ github.repository }}
            Ветка: ${{ github.ref_name }}
            Коммит: ${{ github.sha }}
            Номер запуска: ${{ github.run_number }}
            Автор: ${{ github.actor }}

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install project dependencies
        run: |
          npm ci

      - name: Run code linting
        id: lint
        run: |
          npm run lint

      - name: Send Telegram notification - Lint success
        if: success() && steps.lint.conclusion == 'success'
        uses: appleboy/telegram-action@v0.1.1
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            ✅ Проверка линтером успешно завершена!
            Репозиторий: ${{ github.repository }}
            Ветка: ${{ github.ref_name }}
            Коммит: ${{ github.sha }}
            Номер запуска: ${{ github.run_number }}

      - name: Send Telegram notification - Lint failed
        if: failure()
        uses: appleboy/telegram-action@v0.1.1
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            ❌ Проверка линтером провалена!
            Репозиторий: ${{ github.repository }}
            Ветка: ${{ github.ref_name }}
            Коммит: ${{ github.sha }}
            Номер запуска: ${{ github.run_number }}
            Проверьте логи workflow для получения деталей.

    outputs:
      lint_status: ${{ job.status }}

  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: lint-check
    if: needs.lint-check.result == 'success'
    permissions:
      contents: read
    
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Send Telegram notification - Tests started
        uses: appleboy/telegram-action@v0.1.1
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            🧪 Начался запуск тестов!
            Репозиторий: ${{ github.repository }}
            Ветка: ${{ github.ref_name }}
            Коммит: ${{ github.sha }}
            Номер запуска: ${{ github.run_number }}
            Автор: ${{ github.actor }}

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install project dependencies
        run: |
          npm ci

      - name: Create .env file from secrets
        env:
          API_KEY: ${{ secrets.API_KEY }}
          USER_LOGIN: ${{ secrets.USER_LOGIN }}
          USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
          OPEN_API_URL: ${{ secrets.OPEN_API_URL }}
          URL_CRM: ${{ secrets.URL_CRM }}
        run: |
          echo "API_KEY=$API_KEY" > .env
          echo "USER_LOGIN=$USER_LOGIN" >> .env
          echo "USER_PASSWORD=$USER_PASSWORD" >> .env
          echo "OPEN_API_URL=$OPEN_API_URL" >> .env
          echo "URL_CRM=$URL_CRM" >> .env
          echo "Созданный .env файл:"
          cat .env

      - name: Install Playwright browsers
        run: |
          npx playwright install --with-deps

      - name: Run tests
        id: tests
        run: |
          npm run test

      - name: Send Telegram notification - Tests success
        if: success() && steps.tests.conclusion == 'success'
        uses: appleboy/telegram-action@v0.1.1
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            ✅ Все тесты успешно пройдены!
            Репозиторий: ${{ github.repository }}
            Ветка: ${{ github.ref_name }}
            Коммит: ${{ github.sha }}
            Номер запуска: ${{ github.run_number }}

      - name: Send Telegram notification - Tests failed
        if: failure()
        uses: appleboy/telegram-action@v0.1.1
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            ❌ Тесты провалены!
            Репозиторий: ${{ github.repository }}
            Ветка: ${{ github.ref_name }}
            Коммит: ${{ github.sha }}
            Номер запуска: ${{ github.run_number }}
            Проверьте логи workflow для получения деталей.

    outputs:
      tests_status: ${{ job.status }}

  deploy-report:
    name: Deploy Test Report
    runs-on: ubuntu-latest
    needs: run-tests
    if: needs.run-tests.result == 'success'
    permissions:
      contents: read

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.DEPLOY_GH_PAGES_TOKEN }}
          publish_dir: ./test-results/html-report
          commit_message: "Deploy test report: ${{ github.sha }}"

      - name: Send Telegram notification - Report deployed
        if: success()
        uses: appleboy/telegram-action@v0.1.1
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            📊 Отчет о тестах задеплоен в GitHub Pages!
            Репозиторий: ${{ github.repository }}
            Ветка: ${{ github.ref_name }}
            Коммит: ${{ github.sha }}
            Номер запуска: ${{ github.run_number }}
            URL: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/

      - name: Send Telegram notification - Deploy failed
        if: failure()
        uses: appleboy/telegram-action@v0.1.1
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            ❌ Ошибка при деплое отчета в GitHub Pages!
            Репозиторий: ${{ github.repository }}
            Ветка: ${{ github.ref_name }}
            Коммит: ${{ github.sha }}
            Номер запуска: ${{ github.run_number }}