name: Playwright API Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 🚀 Уведомление о старте в Telegram
        run: |
          curl -s -X POST \
            "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
            -d text="<b>Запуск автотестов</b>Проект: <code>${{ github.repository }}</code>\nЗапуск: $GITHUB_RUN_ID\nВетка: $GITHUB_REF_NAME" \
            -d parse_mode=HTML

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install chromium

      - name: Create .env file from secrets
        env:
          API_KEY: ${{ secrets.API_KEY }}
          USER_LOGIN: ${{ secrets.USER_LOGIN }}
          USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
          OPEN_API_URL: ${{ secrets.OPEN_API_URL }}
          URL_CRM: ${{ secrets.URL_CRM }}
        run: |
          echo "API_KEY=$API_KEY" > .env
          echo "USER_LOGIN=$USER_LOGIN" >> .env
          echo "USER_PASSWORD=$USER_PASSWORD" >> .env
          echo "OPEN_API_URL=$OPEN_API_URL" >> .env
          echo "URL_CRM=$URL_CRM" >> .env
          cat .env 

      - name: Run Playwright tests
        id: playwright
        continue-on-error: true
        run: npx playwright test --config=playwright.config.js

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: test-results/
          retention-days: 7

      - name: 📬 Отправить результат в Telegram
        if: always()
        run: |
          if [ "${{ steps.playwright.outcome }}" = "success" ]; then
            TEXT="✅ <b>Тесты пройдены!</b><a href='https://brcd7735.github.io/API_CRM_playwright/ '>Открыть отчет</a>"
          else
            TEXT="❌ <b>Тесты упали!</b><a href='https://brcd7735.github.io/API_CRM_playwright/ '>Открыть отчет</a>"
          fi

          curl -s -X POST \
            "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage"\
            -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}"\
            -d text="$TEXT"\
            -d parse_mode=HTML

      - name: Deploy to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.DEPLOY_GH_PAGES_TOKEN }}
          publish_dir: ./test-results/html-report
          commit_message: ${{ github.sha }}