name: Playwright API Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 🚀 Уведомление о старте в Telegram
        run: |
          TEXT="🚀 *Запуск автотестов*\n\n"
          TEXT+="📂 Проект: `${{ github.repository }}`\n"
          TEXT+="🔢 Запуск: $GITHUB_RUN_ID\n"
          TEXT+="🧩 Ветка: $GITHUB_REF_NAME\n"
          TEXT+="⏰ Время: $(date '+%H:%M:%S %d.%m.%Y')"

          curl -s -X POST \
            "https://api.telegram.org/bot ${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
            -d text="$TEXT" \
            -d parse_mode=MarkdownV2

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install chromium

      - name: Create .env file from secrets
        env:
          API_KEY: ${{ secrets.API_KEY }}
          USER_LOGIN: ${{ secrets.USER_LOGIN }}
          USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
          OPEN_API_URL: ${{ secrets.OPEN_API_URL }}
          URL_CRM: ${{ secrets.URL_CRM }}
        run: |
          echo "API_KEY=$API_KEY" > .env
          echo "USER_LOGIN=$USER_LOGIN" >> .env
          echo "USER_PASSWORD=$USER_PASSWORD" >> .env
          echo "OPEN_API_URL=$OPEN_API_URL" >> .env
          echo "URL_CRM=$URL_CRM" >> .env
          cat .env 

      - name: Run Playwright tests
        id: playwright
        continue-on-error: true
        run: npx playwright test --config=playwright.config.js

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: test-results/
          retention-days: 7

      - name: 📬 Отправить результат в Telegram
        if: always()
        run: |
        # Проверяем реальный результат тестов
         if [ "${{ steps.playwright.outcome }}" = "success" ]; then
          TEXT="✅ *Тесты пройдены!*\n\n"
         else
           TEXT="❌ *Тесты не пройдены!*\n\n"
         fi

      # Добавляем детали
         TEXT+="🚀 *Результаты автотестов*\n"
         TEXT+="📂 Проект: `${{ github.repository }}`\n"
         TEXT+="🔢 Прогон: $GITHUB_RUN_ID\n"
         TEXT+="📅 Дата: $(date '+%d.%m.%Y %H:%M:%S')\n"
         TEXT+="🔗 [Открыть отчет автотестов](https://brcd7735.github.io/API_CRM_playwright/)"
      
      # Отправляем в Telegram
         curl -s -X POST \
          "https://api.telegram.org/bot ${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
          -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
          -d text="$TEXT" \
          -d parse_mode=MarkdownV2  # ← Изменение здесь

      - name: Deploy to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.DEPLOY_GH_PAGES_TOKEN }}
          publish_dir: ./test-results/html-report
          commit_message: ${{ github.sha }}