name: Playwright API Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: ⏱ Запомнить время старта
        run: |
          echo "START_TIME=$(date +%s)" >> $GITHUB_ENV
      - name: 🚀 Уведомление о старте в Telegram
        run: |
          curl -s -X POST \
            "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
            -d text="<b>Запуск автотестов</b>Проект: <code>${{ github.repository }}</code>\nЗапуск: $GITHUB_RUN_ID\nВетка: $GITHUB_REF_NAME" \
            -d parse_mode=HTML

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install chromium

      - name: Create .env file from secrets
        env:
          API_KEY: ${{ secrets.API_KEY }}
          USER_LOGIN: ${{ secrets.USER_LOGIN }}
          USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
          OPEN_API_URL: ${{ secrets.OPEN_API_URL }}
          URL_CRM: ${{ secrets.URL_CRM }}
        run: |
          echo "API_KEY=$API_KEY" > .env
          echo "USER_LOGIN=$USER_LOGIN" >> .env
          echo "USER_PASSWORD=$USER_PASSWORD" >> .env
          echo "OPEN_API_URL=$OPEN_API_URL" >> .env
          echo "URL_CRM=$URL_CRM" >> .env
          cat .env 

      - name: Run Playwright tests
        id: playwright
        continue-on-error: true
        run: npx playwright test --config=playwright.config.js

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: test-results/
          retention-days: 7

      - name: 📬 Отправить результат в Telegram
        if: always()
        run: |
          # Получаем время начала и конца в секундах
          START_TIME=${{ env.START_TIME }}
          END_TIME=$(date +%s)
          DURATION=$((END_TIME - START_TIME))

          # Форматируем: 65 сек → 1 мин 5 сек
          MINUTES=$((DURATION / 60))
          SECONDS=$((DURATION % 60))
          if [ $MINUTES -gt 0 ]; then
            DURATION_STR="${MINUTES} мин ${SECONDS} сек"
          else
            DURATION_STR="${SECONDS} сек"
          fi

          # Формируем текст
          if [ "${{ steps.playwright.outcome }}" = "success" ]; then
            TEXT="✅ <b>Тесты пройдены!</b>\n\n"
          else
            TEXT="❌ <b>Тесты упали!</b>\n\n"
          fi

          TEXT+="📂 Проект: <code>${{ github.repository }}</code>\n"
          TEXT+="🔢 Прогон: $GITHUB_RUN_ID\n"
          TEXT+="⏱ Время выполнения: $DURATION_STR\n"
          TEXT+="📅 Дата: $(date '+%d.%m.%Y %H:%M:%S')\n"
          TEXT+="🔗 <a href='https://brcd7735.github.io/API_CRM_playwright/'>Открыть HTML-отчёт</a>"

          # Отправляем
          curl -s -X POST \
            "https://api.telegram.org/bot ${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
            -d text="$TEXT" \
            -d parse_mode=HTML

      - name: Deploy to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.DEPLOY_GH_PAGES_TOKEN }}
          publish_dir: ./test-results/html-report
          commit_message: ${{ github.sha }}