name: Playwright API Tests

# Запуск при пушах и PR в основные ветки
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 🔁 1. Клонировать репозиторий
      - name: Checkout code
        uses: actions/checkout@v4

      # 🟦 2. Установить Node.js (версия из .nvmrc или указанная)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      # 📦 3. Установить зависимости
      - name: Install dependencies
        run: npm ci

      # 🧪 4. Установить Playwright browsers (даже для API нужны браузеры, если используется Playwright)
      - name: Install Playwright browsers
        run: npx playwright install-deps  # гарантирует установку системных зависимостей
        # Если не нужен UI, можно использовать: playwright install --no-deps

      # 🔐 5. Загрузить .env файл (API ключ) из секретов GitHub
      - name: Create .env file from secrets
        env:
          API_KEY: ${{ secrets.API_KEY }},
          USER_LOGIN: ${{ secrets.USER_LOGIN }},
          USER_PASSWORD: ${{ secrets.USER_PASSWORD }},
          OPEN_API_URL: ${{ secrets.OPEN_API_URL }},
          URL_CRM: ${{ secrets.URL_CRM }}
        run: |
          echo "API_KEY=$API_KEY" > .env
          cat .env  # Для отладки (не покажет значение, если secret)

      # ▶️ 6. Запустить тесты Playwright
      - name: Run Playwright tests
        run: npx playwright test --config=playwright.config.js --reporter=list,json
        # Сохраняем JSON-отчёт для анализа

      # 📎 7. Сохранить отчёт (опционально)
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: test-results/
          retention-days: 7